name: phpunit

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  phpunit:
    if: "!contains(github.event.head_commit.message, '--skip-ci')"
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: [7.3, 7.4]
        include:
          - laravel: 5.2
            testbench: ^3.2
          - laravel: 5.8
            testbench: ^3.8
            
    name: PHP ${{ matrix.php }} - L${{ matrix.laravel }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up PHP ${{ matrix.php }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}

    - name: Get Composer Cache Directory
      id: composer-cache
      run: |
        echo "::set-output name=dir::$(composer config cache-files-dir)"
    - uses: actions/cache@v3
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-

    - name: Install dependencies
      run: |
          composer require "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --prefer-dist --no-interaction

    - name: Execute tests
      run: vendor/bin/phpunit
